# Client deploy configuration
#
# https://docs.netlify.com/configure-builds/file-based-configuration
#

[build]
  node_version = "14"
  command = "npx browserslist@latest --update-db && yarn build"
  base = "packages/client"
